sudo: required

language: python

services:
  - docker

install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 'https://docker.clarin.eu/'
  - docker pull 'docker.clarin.eu/debian-monitoring:latest'
  - docker create --attach --entrypoint='/bin/sh' --name='debian-monitoring-latest' --volume="$(readlink -f 'resources/srv/'):/srv/" 'docker.clarin.eu/debian-monitoring:latest' -c 'cd "/srv/" && ./test.sh'

script:
  - docker start 'debian-monitoring-latest'