sudo: required

language: python

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 'https://docker.clarin.eu/'
  - docker pull 'docker.clarin.eu/debian-monitoring:latest'
  - docker create --name='debian-monitoring-latest' --volume="$(realpath resources/srv/):/srv/" --entrypoint='/bin/sh' 'docker.clarin.eu/debian-monitoring:latest'
  - docker start 'debian-monitoring-latest'

script:
  - cd '/srv/' && ./test.sh