This virtualized application/service consists of the CLARIN monitoring setup. This repository can be used to build e.g. a Docker container image. The dependencies and other resources are under link:resources/[`resources/`].

== Requirements

* https://packer.io[Packer].
* https://www.docker.com/[Docker].

=== Suggested requirements

* The `readlink` command-line utility, offered by http://www.gnu.org/software/coreutils/coreutils.html[GNU coreutils].
* https://www.sudo.ws/[`sudo`].

== To build

* Follow this https://github.com/sanmai-NL/guide_on_submodules[brief guide on submodules] to learn how to manage dependency submodules, if you do not know it already. Complete https://github.com/sanmai-NL/recursive_packer_build/blob/master/Project_dependencies_as_Git_submodules.adoc#getting-started-with-a-git-repository-that-has-submodules[the recursive clone] or submodule initialization of this repository.
* Complete a https://github.com/sanmai-NL/recursive_packer_build#to-use[recursive Packer build].

== To configure

* First make sure your current working directory is the root directory of your local copy of this repository, and that the previously described build process has completed successfully.
* Then issue:
[source,Sh]
----
docker create \
    --entrypoint='/bin/bash' \
    --name='debian-monitoring-latest' \
    --tty=true \
    --volume="$(readlink -f 'resources/srv/'):/srv/" \
    'docker.clarin.eu/debian-monitoring:latest'
----

== To run

[source,Sh]
----
docker start 'debian-monitoring-latest'
----

== To test

Travis CI pulls this Docker container image from the CLARIN Docker Registry, and then performs the tests by executing link:resources/srv/test.sh[`resources/srv/test.sh`]. This script file is mapped to `/srv/test.sh` within the container by default.